# coding: utf-8


meta:
    site_title: "白日门 Young's Blog"
    site_subtitle: "岁月之门"
    site_language: "zh-cn"
    absolute_baseurl: http://bairimen.github.com
    domain: bairimen.github.com
    author:
        full_name: Cong Young
        short_name: Young
        name: Young
        email: Young@Young.org

url: http://bairimen.github.com

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false

#permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

lsi: false



